_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: ccb35d05-43b5-41cf-851d-5c9151d23ddb
name: appbook
mail: carfelcoper@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /book-list
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
